# Random Forest Classifier in NPF Data

### Testing Random forest classifier

In [31]:
import pandas as pd
import numpy as np

npf = pd.read_csv("npf_train.csv")
npf_test = pd.read_csv("npf_test_hidden.csv")

npf = npf.set_index("date")
npf = npf.drop("id", axis=1)
npf = npf.drop("partlybad", axis=1)

npf_test = npf_test.set_index("date")
npf_test = npf_test.drop("id", axis=1)
npf_test = npf_test.drop("partlybad", axis=1)

class2 = np.array(["nonevent", "event"])
npf["class2"] = class2[(npf["class4"]!="nonevent").astype(int)]
npf_test["class2"] = class2[(npf_test["class4"]!="nonevent").astype(int)]

npf

,class4,CO2168.mean,CO2168.std,CO2336.mean,CO2336.std,CO242.mean,CO242.std,CO2504.mean,CO2504.std,Glob.mean,...,T672.std,T84.mean,T84.std,UV_A.mean,UV_A.std,UV_B.mean,UV_B.std,CS.mean,CS.std,class2
date,,,,,,,,,,,,,,,,,,,,,
2000-01-17,Ib,368.771711,0.310309,368.665658,0.305127,369.371184,0.333606,368.616053,0.302364,41.650106,...,0.250952,-0.899393,0.271648,2.492491,1.310880,0.031587,0.018122,0.000243,0.000035,event
2000-02-28,nonevent,378.197295,1.001493,378.083089,1.025472,378.671311,1.017208,378.029508,1.022258,3.478842,...,0.313460,2.033191,0.271090,0.295937,0.177836,0.005140,0.003552,0.003658,0.000940,nonevent
2000-03-24,Ib,373.043158,0.749865,372.930066,0.728411,373.569735,0.835240,372.869868,0.692828,297.954063,...,2.037111,0.780422,2.334741,14.434789,8.627312,0.353743,0.272472,0.000591,0.000191,event
2000-03-30,II,375.643019,0.558629,375.549430,0.540964,376.045849,0.580730,375.506013,0.529970,324.318386,...,2.509758,6.533544,2.695277,16.077513,9.984686,0.568242,0.451830,0.002493,0.000466,event
2000-04-04,nonevent,377.661030,0.408421,377.609576,0.423963,378.117134,0.417243,377.582242,0.424460,167.479964,...,1.438071,2.133774,1.614122,9.710422,7.054069,0.339135,0.291457,0.004715,0.000679,nonevent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2011-08-16,nonevent,381.016623,4.411571,381.030844,4.062115,382.901742,5.061991,381.072078,3.840630,121.227780,...,1.089563,17.268471,1.308728,8.688739,8.320799,0.464422,0.496816,0.002423,0.000425,nonevent
2011-08-19,nonevent,383.698146,8.418351,384.052632,8.130389,386.436800,9.901536,384.105592,7.952936,332.744478,...,2.868514,16.352391,3.055122,18.475262,12.838481,0.884404,0.726461,0.002476,0.000902,nonevent
2011-08-21,nonevent,379.279128,12.045785,379.363087,11.533353,381.268591,14.043508,379.163200,10.932955,114.298822,...,1.696894,15.094141,1.745526,8.099394,5.851942,0.416961,0.363890,0.003484,0.000457,nonevent
2011-08-22,nonevent,384.443758,6.413297,384.364392,5.781036,386.384762,7.663215,384.186892,5.506259,180.454576,...,0.969001,16.076217,1.197644,11.665070,10.062797,0.622831,0.595032,0.004782,0.001082,nonevent
2011-08-27,nonevent,382.230839,6.407469,382.448601,6.242533,384.061748,7.748701,382.502587,6.174042,297.137573,...,2.466867,21.946135,2.604069,16.670267,11.216294,0.899029,0.722553,0.006956,0.000605,nonevent

### Splitting train and test data

In [32]:
from sklearn.model_selection import train_test_split

X_train = npf.drop(["class4", "class2"], axis=1)
y_train = npf["class2"]

X_test = npf_test.drop(["class4", "class2"], axis=1)
y_test = npf_test["class2"]

### Trying feature selection

In [38]:
from sklearn.feature_selection import SelectKBest, f_classif

selector = SelectKBest(f_classif, k=5)
selector.fit_transform(X_train, y_train)

cols = selector.get_support(indices=True)
X_new = X_train.iloc[:,cols]
X_new

,RHIRGA168.mean,RHIRGA336.mean,RHIRGA42.mean,RHIRGA504.mean,RHIRGA84.mean
date,,,,,
2000-01-17,74.345921,74.066842,74.900921,74.543421,74.509200
2000-02-28,100.283197,99.753984,99.619180,100.227623,99.240574
2000-03-24,57.051184,57.530132,56.786623,58.060066,56.476316
2000-03-30,67.839057,68.467025,67.020000,69.449051,67.095220
2000-04-04,88.100848,89.108364,86.910732,90.234727,86.864424
...,...,...,...,...,...
2011-08-16,77.766299,78.929675,77.138323,79.537987,77.203052
2011-08-19,60.188278,60.114079,63.270067,59.979145,62.037815
2011-08-21,77.193490,77.896242,77.170134,78.177800,76.968926
2011-08-22,75.909799,77.035270,75.236463,77.703108,75.097114
2011-08-27,59.074336,59.845874,59.481538,60.131748,58.908042

In [56]:
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import RandomForestClassifier

m = SelectFromModel(RandomForestClassifier())
m.fit(X_train, y_train)

columns = m.get_support(indices=True)
X_new = X_train.iloc[:,columns]

X_new

,CO2336.std,CO2504.std,Glob.mean,H2O168.mean,H2O336.mean,H2O42.mean,H2O504.mean,H2O672.mean,H2O84.mean,NET.std,...,RHIRGA504.std,RHIRGA672.mean,RHIRGA84.mean,RHIRGA84.std,SWS.mean,T168.mean,T42.mean,T672.mean,UV_A.mean,CS.mean
date,,,,,,,,,,,,,,,,,,,,,
2000-01-17,0.305127,0.302364,41.650106,4.383158,4.358684,4.448289,4.351579,4.349342,4.422000,23.997837,...,3.068035,76.355395,74.509200,3.153985,937.880000,-0.996623,-0.899631,-1.476016,2.492491,0.000243
2000-02-28,1.025472,1.022258,3.478842,7.233852,7.172114,7.251721,7.166230,7.121724,7.219590,11.837190,...,0.915969,101.839224,99.240574,0.816601,936.000000,1.911915,2.044877,1.479493,0.295937,0.003658
2000-03-24,0.728411,0.692828,297.954063,3.575000,3.553026,3.621523,3.540331,3.539536,3.592039,150.941475,...,13.600660,59.608742,56.476316,14.347865,923.745098,0.541530,0.815106,-0.270844,14.434789,0.000591
2000-03-30,0.540964,0.529970,324.318386,6.500566,6.512278,6.515472,6.512152,6.519430,6.512642,156.370048,...,8.580606,71.324747,67.095220,8.855484,925.622642,6.339887,6.561362,5.622308,16.077513,0.002493
2000-04-04,0.423963,0.424460,167.479964,6.223576,6.213879,6.269451,6.218667,6.223394,6.240667,128.783783,...,7.980392,92.905455,86.864424,8.428027,921.727273,1.885328,2.180546,1.140121,9.710422,0.004715
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2011-08-16,4.062115,3.840630,121.227780,15.121299,15.068442,15.224194,15.026299,14.995519,15.189351,116.719178,...,5.439746,80.831494,77.203052,5.952540,915.250000,17.075372,17.323382,16.319361,8.688739,0.002423
2011-08-19,8.130389,7.952936,332.744478,10.946556,10.760329,11.328859,10.641908,10.550927,11.183046,222.197400,...,17.189884,60.453642,62.037815,16.718655,890.500000,16.469414,16.245874,15.820245,18.475262,0.002476
2011-08-21,11.533353,10.932955,114.298822,13.131946,13.056040,13.218322,13.013600,12.995638,13.185101,89.941820,...,6.380528,79.196711,76.968926,5.911362,879.032258,14.991524,15.087546,14.421092,8.099394,0.003484
2011-08-22,5.781036,5.506259,180.454576,13.616242,13.554527,13.691429,13.521486,13.487838,13.667114,149.243111,...,6.717325,78.934324,75.097114,7.115798,883.048387,15.836196,16.073609,15.049728,11.665070,0.004782
2011-08-27,6.242533,6.174042,297.137573,15.116923,15.003147,15.321538,14.927133,14.845000,15.255385,200.931287,...,13.482388,60.880694,58.908042,11.915897,915.350000,21.788000,21.910180,21.040539,16.670267,0.006956

In [24]:
from sklearn.ensemble import RandomForestClassifier


forest = RandomForestClassifier()
print(forest.get_params())

forest.fit(X_train, y_train)

forest.score(X_test, y_test)

{'bootstrap': True, 'ccp_alpha': 0.0, 'class_weight': None, 'criterion': 'gini', 'max_depth': None, 'max_features': 'auto', 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'n_estimators': 100, 'n_jobs': None, 'oob_score': False, 'random_state': None, 'verbose': 0, 'warm_start': False}

0.43937823834196893

## Conclusions 18.11.

Using sklearn SelectFromModel feature selection algroithm scales the dataset down to about 26 columns. We could also use SelectKBest algorithm, but SelectFromModel is simpler and provides good results.

A very good guide to hyperparameter optimization: https://towardsdatascience.com/hyperparameter-tuning-the-random-forest-in-python-using-scikit-learn-28d2aa77dd74
Will follow this to get best parameters for random forest